Almacen/Models/Data/User.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace Almacen.Models.Data
{
    public class User : IdentityUser
    {
        [Required]
        public string Address { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Province { get; set; }
        [Required]
        [MaxLength(5)]
        public string ZipCode { get; set; }
        [MaxLength(12)]
        public string DNI { get; set; }
        [MaxLength(75)]
        public string Name { get; set; }
        [MaxLength(50)]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime RegisterDate { get; set; }

        public ICollection<Order> Orders { get; set; }
        public SupplierEnterprise SupplierEnterprise { get; set; }
        public ICollection<Make> Makes { get; set; }
    }
}

Almacen/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Almacen.Models.Data;
using Almacen.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Almacen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Almacen.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private UserManager<User> userManager;
        private IOrderRepository repository;
        private Cart cartService;

        public OrderController(UserManager<User> usrMgr, Cart cart, IOrderRepository repoService)
        {
            userManager = usrMgr;
            cartService = cart;
            repository = repoService;
        }

        public async Task<IActionResult> Checkout(string username)
        {
            OrdersViewModel ordersView;
            if (!string.IsNullOrEmpty(username))
            {
                ordersView = new OrdersViewModel();
                User user = await userManager.FindByNameAsync(username);
                if (user != null)
                {
                    ordersView.Cart = cartService;
                    ordersView.User = user;
                }
                return View(ordersView);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> CheckOut(User user)
        {
            User clientUser = await userManager.FindByIdAsync(user.Id);
            if(cartService.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "El carro de compras está vacío");
            }
            if(ModelState.IsValid && clientUser != null)
            {
                Order order = new Order();
                order.Lines = cartService.Lines.ToArray();
                order.Client = clientUser;
                order.OrderDateTime = DateTime.Now;
                order.Delivered = false;
                order.Rejected = false;
                repository.SaveOrder(order);
            }
            cartService.Clear();
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles ="Admin,Employee")]
        public async Task<IActionResult> Index()
        {
            List<Order> orders = repository.Orders.Include(u => u.Client).Include(e => e.Employee)
                .OrderBy(o => o.OrderDateTime).ToList();
            List<BasicOrderData> basicOrderDatas = new List<BasicOrderData>();


            foreach(Order order in orders)
            {
                if (string.IsNullOrEmpty(order.Client.Id))
                    break;
                BasicOrderData orderDetails = await GetBasicOrderData(order);
                basicOrderDatas.Add(orderDetails);
            }

            return View(basicOrderDatas);
        }

        public async Task<IActionResult> Details(string orderid)
        {
            Order order = repository.Orders.Include(u => u.Client)
                .Include(e => e.Employee).FirstOrDefault(o => o.Id == orderid);
            return View(await GetBasicOrderData(order));
        }

        private async Task<BasicOrderData> GetBasicOrderData(Order order)
        {
            if (order == null)
                return null;
            if (order.Client == null)
                return null;
            BasicOrderData data = new BasicOrderData();
            User client = await userManager.FindByIdAsync(order.Client.Id);
            User employee = null;

            data.Client = order.Client;

            if (order.Employee != null)
            {
                employee = await userManager.FindByIdAsync(order.Employee.Id);
                data.Employee = employee;
            }

            data.TotalPrice = order.Lines.Sum(p => p.Product.Price * p.Quantity);
            data.Order = order;
            
            return data;
        }

    }
}

Almacen/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Almacen.Models.Data;
using Almacen.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Almacen.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleAdminController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<User> userManager;

        public RoleAdminController(RoleManager<IdentityRole> roleMan, UserManager<User> usrMgr)
        {
            roleManager = roleMan;
            userManager = usrMgr;
        }

        public IActionResult Index()
        {
            return View(roleManager.Roles);
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<User> members = new List<User>();
            List<User> nonMembers = new List<User>();

            foreach(User user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                    members.Add(user);
                else
                    nonMembers.Add(user);
            }
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    User user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    User user = await userManager.FindByIdAsync(userId);
                    if(user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if(!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
            }
            if(ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return await Edit(model.RoleId);
            }
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach(IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

Almacen/Views/Admin/Edit.cshtml
@model User

@{
    ViewData["Title"] = "Editar Usuario";
}

<div class="bg-primary m-1 p-1 text-white"><h4>Editar Usuario</h4></div>
<div asp-validation-summary="All" class="alert alert-danger"></div>

<form asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input name="password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

Almacen/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Administración - Inicio";
}

<div class="bg-primary m-1 p-1 text-white"><h4>@ViewData["Title"]</h4></div>

@if(User.IsInRole("Admin") || User.IsInRole("Employee"))
{
    <div class="bg-info m-1 p-1 text-white"><h5>Pedidos</h5></div>

    <a asp-controller="Order" 
       asp-action="Index"
       class="btn btn-primary text-white">
    Ver pedidos
</a>
}

@if (User.IsInRole("Admin"))
{
    <div class="bg-info m-1 p-1 text-white"><h5>Usuarios</h5></div>
    <a asp-action="Users" class="btn btn-primary text-white">Administrar usuarios</a>

    <div class="bg-info m-1 p-1 text-white"><h5>Roles</h5></div>
    <a asp-controller="RoleAdmin"
       asp-action="Index"
       class="btn btn-primary text-white">Administrar roles</a>
}

Almacen/Views/Admin/Users.cshtml
@model IEnumerable<User>

@{
    ViewData["Title"] = "Administración - Usuarios";
}

<div class="bg-primary m-1 p-1 text-white"><h4>@ViewData["Title"]</h4></div>
<div class="bg-info p-1 text-white"><h5>Cuentas de usuarios</h5></div>
<table class="table table-sm table-bordered table-striped table-hover">
    <tr><th>ID</th><th>Nombre de usuario</th><th>Email</th><th>Editar</th><th>Borrar</th></tr>
    @if (Model.Count() == 0)
    {
        <tr><th colspan="5" class="text-center">No hay cuentas de usuario</th></tr>
    }
    else
    {
        foreach (User user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Editar</a>
                </td>
                <td>
                    <form asp-controller="Account" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@user.Id" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Borrar
                        </button>
                    </form>
                </td>
            </tr>
        }
    }
</table>

<a asp-action="Index" class="btn btn-primary text-white">Volver</a>