Almacen/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Almacen.Models.Data;

namespace Almacen.Models.ViewModels
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke() => View(cart);
    }
}

Almacen/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Almacen.Models.ViewModels;
using Almacen.Models;
using Almacen.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace Almacen.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;

        public ProductController(IProductRepository rep)
        {
            repository = rep;
        }

        public IActionResult Index(string search, string sortOrder, int? page)
        {
            int productsPerPage = 10;
            ProductsViewModel productsViewModel = new ProductsViewModel();
            IQueryable<Product> products = repository.Products;

            if (page == null)
                page = 1;

            ViewData["NameSortParam"] = sortOrder == "name" ? "name_des" : "name";
            ViewData["QuantSortParam"] = sortOrder == "quant" ? "quant_des" : "quant";
            ViewData["BrandSortParam"] = sortOrder == "brand" ? "brand_des" : "brand";
            ViewData["CatSortParam"] = sortOrder == "cat" ? "cat_des" : "cat";
            ViewData["CostPriceSortParam"] = sortOrder == "costPrice" ? "costPrice_des" : "costPrice";
            ViewData["PriceSortParam"] = sortOrder == "price" ? "price_des" : "price";
            ViewData["CurrentFilter"] = search;


            if (!string.IsNullOrEmpty(search))
            {
                products =
                    products.Where(p => p.Name.Contains(search) || 
                    p.Brand.Contains(search) || 
                    p.Description.Contains(search) ||
                    p.Category.Contains(search));
            }

            if(!string.IsNullOrEmpty(sortOrder))
            {
                switch(sortOrder)
                {
                    case "name":
                        products = products.OrderBy(p => p.Name);
                        break;
                    case "name_des":
                        products = products.OrderByDescending(p => p.Name);
                        break;
                    case "quant":
                        products = products.OrderBy(p => p.Quantity);
                        break;
                    case "quant_des":
                        products = products.OrderByDescending(p => p.Quantity);
                        break;
                    case "brand":
                        products = products.OrderBy(p => p.Brand);
                        break;
                    case "brand_des":
                        products = products.OrderByDescending(p => p.Brand);
                        break;
                    case "cat":
                        products = products.OrderBy(p => p.Category);
                        break;
                    case "cat_des":
                        products = products.OrderByDescending(p => p.Category);
                        break;
                    case "costPrice":
                        products = products.OrderBy(p => p.CostPrice);
                        break;
                    case "costPrice_des":
                        products = products.OrderByDescending(p => p.CostPrice);
                        break;
                    case "price":
                        products = products.OrderBy(p => p.Price);
                        break;
                    case "price_des":
                        products = products.OrderByDescending(p => p.Price);
                        break;
                    default:
                        products = products.OrderBy(p => p.Id);
                        break;
                }   
            }

            productsViewModel.LastSortParam = sortOrder;
            productsViewModel.CurrentPage = (int)page;
            if ((products.Count() % productsPerPage) == 0)
                productsViewModel.MaxPage = (products.Count() / productsPerPage);
            else
                productsViewModel.MaxPage = (products.Count() / productsPerPage) + 1;
            productsViewModel.Products = products.Skip(productsPerPage * ((int)page - 1))
                                                 .Take(productsPerPage);

            return View(productsViewModel);
            //return View(products);
        }

        public ViewResult Edit(string id)
        {
            return View(repository.Products.FirstOrDefault(p => p.Id == id));
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if(ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = $"¡Operación realizada con éxito!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }
    }
}

Almacen/Views/Shared/LoginPartialView.cshtml
@using Microsoft.AspNetCore.Identity

    <ul class="navbar-nav ml-auto">
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-link"
                   asp-controller="Account"
                   asp-action="Edit"
                   asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()"
                   asp-route-username="@User.Identity.Name">@User.Identity.Name</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="\Account\Logout">Salir</a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path" class="nav-link">Ingresar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="\Account\Create">Registrar</a>
            </li>
        }
    </ul>

Almacen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/almacen.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.0.13/web-fonts-with-css/css/fontawesome-all.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
</head>
<body class="m-1 p-1 bg-lightblue">
    <nav class="navbar navbar-expand-md navbar-dark bg-darkblue sticky-top">
        <a class="navbar-brand" href="\Home\Index">Inicio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a asp-controller="Product"
                       asp-action="Index"
                       asp-route-page="1"
                       class="nav-link">
                        Productos
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sobre Nosotros</a>
                </li>
                @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="\Admin\Index">Administración</a>
                    </li>
                }
            </ul>

            @if (User.IsInRole("Client"))
            {
                @await Component.InvokeAsync("CartSummary")
            }


            @Html.Partial("LoginPartialView")

        </div>
    </nav>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
    <footer>
        <hr>
        <div>Criolani Alejandro - 2018</div>
    </footer>
</body>
</html>